services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER:postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:postgres}
        POSTGRES_DB: ${POSTGRES_DB:whatsapp_clone}
        PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - "6969:5432"
    networks:
      - whatsapp-clone
    restart: unless-stopped

  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.1.2
    ports:
      - "7474:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:admin}
    networks:
        - whatsapp-clone
    command:
      - "start-dev"
  app:
    image: ncas19/docker_whatsapp:latest
    container_name: whatsapp-clone
    ports:
      - "9999:9999"
    depends_on:
        - postgres
        - keycloak
    networks:
        - whatsapp-clone
    environment:
    - APP_CONTEXT_PATH=
    - APP_PORT=
    - CLOUDINARY_API_KEY=
    - CLOUDINARY_API_SECRET=
    - CLOUDINARY_CLOUD_NAME=
    - HIBERNATE_DDL_AUTO=
    - KEYCLOAK_ISSUER_URI=
    - LOGGING_LEVEL=
    - POSTGRES_DB=
    - POSTGRES_HOST=
    - POSTGRES_PASSWORD=
    - POSTGRES_PORT=
    - POSTGRES_USER=
    - SHOW_SQL=
    - WEBSOCKET_URL=


networks:
    whatsapp-clone:
        driver: bridge

volumes:
    postgres:
      driver: local