services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER:postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:postgres}
        POSTGRES_DB: ${POSTGRES_DB:whatsapp_clone}
        PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - "6969:5432"
    networks:
      - whatsapp-clone
    restart: unless-stopped

  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.1.2
    ports:
      - "7474:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:admin}
    networks:
        - whatsapp-clone
    command:
      - "start-dev"


networks:
    whatsapp-clone:
        driver: bridge

volumes:
    postgres:
      driver: local