server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: ${APP_CONTEXT_PATH:/}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

application:
  title: Whatsapp Clone
  version: 1.0.0
  file:
    uploads:
      media-output:
        path: ./uploads

spring-boot:
  version: 3.4.1

spring:
  application:
    name: whatsapp-clone
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

websocket:
  url: ${WEBSOCKET_URL}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

logging:
  level:
    root: ${LOGGING_LEVEL}
    org.springframework.web: ${LOGGING_LEVEL}
    org.hibernate.dialect: ${LOGGING_LEVEL}
    org.hibernate.SQL: ${LOGGING_LEVEL}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL}
    org.springframework.web.socket.messaging: ${LOGGING_LEVEL}
postgres:
  driverClassName: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect
  url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  user: ${POSTGRES_USER}
  pass: ${POSTGRES_PASSWORD}